# Generated by Django 5.2.3 on 2025-06-28 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del asistente', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del evento (ej: Conferencia Anual 2025)', max_length=200)),
                ('fecha', models.DateField(help_text='Fecha en que se realiza el evento')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('datecompleted', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(help_text='Fecha y hora exactas en que el asistente entra al evento')),
                ('check_out', models.DateTimeField(blank=True, help_text='Fecha y hora exactas en que el asistente sale del evento. Vacío si aún está dentro.', null=True)),
                ('asistente', models.ForeignKey(help_text='Asistente que realiza el check-in/out', on_delete=django.db.models.deletion.CASCADE, to='tasks.asistente')),
                ('evento', models.ForeignKey(help_text='Evento al que se registra la asistencia', on_delete=django.db.models.deletion.CASCADE, to='tasks.evento')),
            ],
            options={
                'ordering': ['-check_in'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('evento', 'asistente'), name='unique_active_checkin_per_event')],
            },
        ),
    ]
