# Generated by Django 5.2.3 on 2025-07-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='check_in',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora exactas de entrada al evento', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='check_out',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora exactas de salida del evento (vacío si sigue dentro)', null=True),
        ),
    ]
