# Generated by Django 5.2.3 on 2025-08-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_evento_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registro',
            name='unique_active_checkin_per_event',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='evento',
        ),
        migrations.AddField(
            model_name='asistente',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='tasks.evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistente',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del asistente', max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asistente',
            unique_together={('evento', 'nombre')},
        ),
        migrations.AddConstraint(
            model_name='registro',
            constraint=models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('asistente',), name='unique_active_checkin_per_assistant'),
        ),
    ]
